all: level0 level1a level1b level2

level0: level0.c
	gcc -o level0 level0.c

level1a: level1a.c
	gcc -o level1a level1a.c -lpthread

level1b: level1b.c
	gcc -o level1b level1b.c -lpthread

level2: level2.c
	gcc -o level2 level2.c -lpthread

